/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useLoader } from "@react-three/fiber";
import { TextureLoader } from "three";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(`./3d/laptop2.gltf`);

  const screenTexture = useLoader(TextureLoader, `./3d/jihyun.jpg`);
  screenTexture.flipY = false;

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bottom.geometry}
        material={nodes.Bottom.material}
        position={[0, 0.02, -0.07]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={nodes.Cube004_1.material}
          position={[0, 0.01, 0.02]}
          scale={[20.87, 3, 17.39]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Keys.geometry}
          material={materials.Keys}
          position={[-0.11, 0, -0.13]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Upper.geometry}
        material={nodes.Upper.material}
        position={[0, 0.03, -0.25]}
        rotation={[1.31, 0, 0]}
        scale={[30, 3, 25]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen.geometry}
          material={materials.Screen}
          position={[0, -0.01, 0.01]}
          scale={[0.035, 0.33, 0.04]}
        >
          <meshBasicMaterial map={screenTexture} />
        </mesh>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stand.geometry}
        material={nodes.Stand.material}
        position={[0.38, 0, -0.29]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere.geometry}
          material={nodes.Sphere.material}
          position={[-0.13, 0.29, 0.02]}
          rotation={[0, 0.15, 0]}
        />
      </mesh>
      <group position={[-0.25, 0.01, -0.14]} rotation={[0, 0.26, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={materials.Paper}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_1.geometry}
          material={materials.Paper2}
        />
      </group>
      <group position={[-0.24, 0.01, -0.1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials.Pencil}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Pencil2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_2.geometry}
          material={materials.Pencil3}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.Background}
      />
    </group>
  );
}

useGLTF.preload(`./3d/laptop2.gltf`);
